extends:
  - standard
  - prettier
  - prettier/standard

parser: babel-eslint

plugins:
  - standard
  - prettier

env:
  browser: true

rules:
  # no-undef: 0
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: false
  no-var: 2
  prefer-const: 2

  # TODO: The following rules should be removed incrementally in order to fully
  # integrate lint rules from the Standard ESLint config and Prettier
